<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>elite_robots</name>
  <version>1.0.0</version>
  <description>Metapackage providing a single installation point for the Elite Robots ROS 2 packages.</description>

  <maintainer email="yanxiaojia@elibot.cn">Ivan</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>elite_robots_calibration</exec_depend>
  <exec_depend>elite_robots_controllers</exec_depend>
  <exec_depend>elite_robots_dashboard_msgs</exec_depend>
  <exec_depend>elite_robots_driver</exec_depend>
  <exec_depend>elite_robots_moveit_config</exec_depend>
  <exec_depend>elite_robots_msgs</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
